default:
  before_script:
    - docker info

test-job1:
  stage: test
  variables:
    IMAGE_TAG: hello:gitlab-$CI_COMMIT_SHORT_SHA
  script:
    - echo "token, ${CI_JOB_TOKEN}"
    - echo "URL, ${CI_REGISTRY}"
    - echo "Image, ${IMAGE_TAG}"

build_image:
  variables:
    IMAGE_TAG: $CI_REGISTRY/vpovetkin/helloworld/hello:gitlab-$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
#    - docker run my-docker-image

#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"
#
#test-job1:
#  stage: test
#  script:
#    - echo "This job tests something"
#
#test-job2:
#  stage: test
#  script:
#    - echo "This job tests something, but takes more time than test-job1."
#    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#    - echo "which simulates a test that runs 20 seconds longer than test-job1"
#    - sleep 20
#
#deploy-prod:
#  stage: deploy
#  script:
#    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#  environment: production