---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse 
- src: https://github.com/bova/vector-role.git
  scm: git
  version: "1.1.0"
  name: vector  
- src: https://github.com/bova/lighthouse-role.git
  scm: git
  version: "1.1.0"
  name: lighthouse 