---
# CLICKHOSE
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse

# VECTOR
- name: Install Vector
  hosts: vector
  roles:
    - role: vector
    
# LIGHTHOUSE
- name:
  hosts: lighthouse
  roles:
    - role: lighthouse