---
clickhouse:
  hosts:
    clickhouse1:
      ansible_host: 158.160.72.200
      ansible_ssh_user: admin
      ansible_become: true
vector:
  hosts:
    vector1:
      ansible_host: 51.250.22.177
      ansible_ssh_user: admin
      ansible_become: true
lighthouse:
  hosts:
    lighthouse1:
      ansible_host: 51.250.26.191
      ansible_ssh_user: admin
      ansible_become: true
